version: '3.9'

services:
  db:
    image: postgres:16.4
    container_name: begunici-postgres
    environment:
      POSTGRES_DB: begunici
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: "1234"
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C"
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
    ports:
      - "5433:5432"  # Изменил порт чтобы избежать конфликтов
    volumes:
      - pgdata:/var/lib/postgresql/data
    command: >
      postgres -c log_statement=all
               -c log_destination=stderr
               -c logging_collector=on
               -c max_connections=200
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d begunici"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    container_name: begunici-web
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DB_HOST=db
      - DB_NAME=begunici
      - DB_USER=admin
      - DB_PASSWORD=1234
      - DB_PORT=5432
      - PYTHONIOENCODING=utf-8
      - LANG=C.UTF-8
      - LC_ALL=C.UTF-8
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "sleep 10 &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

volumes:
  pgdata:
